### ISSUE TITLE
黑曜石相關的物品

### ISSUE THREAD

**Issue by Supercow8787** [whes1015/JavaScript#3]
# 🐞 我發現了一個錯誤

挖黑曜石或黑曜石做的東西不能一次挖掉 有時候會變隱形有時候要挖很多次才會掉
### ▶ 重現步驟

1.

**Comment by whes1015** [comment]
頻率呢？每次挖黑曜石都是這樣嗎？

**Comment by happyandy1121** [comment]
不常發生，發生的時候鑽稿也挖不掉黑曜石

**Comment by happyandy1121** [comment]
挖黑曜石需要2到3次才能被挖除,當時tps20 ping13
